### ISSUE TITLE
FeatureFlag API request new API

### ISSUE THREAD

**Issue by atehrani** [launchdarkly/api-client-java#4]
We would like to see a new API on the FlagsApi that has the ability to compare the flag settings across the environments, so that we can quickly find discrepancies between the configurations across them.

This will help us ensure that the flags are properly configured across them all or not.

**Comment by bwoskow-ld** [comment]
Hi @atehrani ,

First off, apologies for the **very** delayed response.

The good news is that in the two years since you requested this feature, a LaunchDarkly API has been implemented to support comparing flags. This API is utilized by the "compare flags" page in the LaunchDarkly app which you can read about in [our documentation](https://docs.launchdarkly.com/docs/compare-and-copy-flag-settings).

The bad news is that our OpenAPI spec currently specifies this API as accepting just a single `env` request parameter instead of an array of environments, and as `api-client-java` is autogenerated based on the OpenAPI spec, the same is true for this client. This means that you can use api-client-java to programmatically access the flag details for a single environment at a time, but not easily compare across environments.

I've filed a bug on our internal tracker to resolve this discrepancy. In the meantime, you can compare flags by using the UI as documented above, or by directly (outside of this client) using the APIs to [get a flag](https://apidocs.launchdarkly.com/reference#get-feature-flag) or [get flags](https://apidocs.launchdarkly.com/reference#list-feature-flags), or by making multiple requests (one per environment).
